### ISSUE TITLE
French translation

### ISSUE THREAD

**Issue by Angelius782** [CoffeSiberian/truck-tools#10]
hello, i have a friend who don't understand English at all.... and would like use your tool

if you want help for translation in french, contact me i will help you with pleasure ( i'm on your discord server with username AngeliuS ;) )

very good job for your tool

**Comment by Angelius782** [comment]
( i'm on your discord server with username AngeliuS ;) )

**Comment by CoffeSiberian** [comment]
Hi there. I'm glad to hear that you like my utility and of course, all help is welcome for the app but at the moment I'm working on the templates for the translations. When these are available in the main branch of the project you are free to start translating the application using the templates

https://github.com/CoffeSiberian/truck-tools/pull/9

**Comment by Angelius782** [comment]
you can use weblate, free on your server or on theirs... but i don't know if you must pay or not for your project

________________________________
De : Fernando Garrido ***@***.***>
Envoyé : mercredi 25 décembre 2024 23:22
À : CoffeSiberian/truck-tools ***@***.***>
Cc : Angelius782 ***@***.***>; Author ***@***.***>
Objet : Re: [CoffeSiberian/truck-tools] French translation (Issue #10)


Hi there. I'm glad to hear that you like my utility and of course, all help is welcome for the app but at the moment I'm working on the templates for the translations. When these are available in the main branch of the project you are free to start translating the application using the templates

#9<https://github.com/CoffeSiberian/truck-tools/pull/9>

**Comment by Angelius782** [comment]
sorry, i forgot to ask, where is the template for translation ^^
________________________________
De : Fernando Garrido ***@***.***>
Envoyé : mercredi 25 décembre 2024 23:22
À : CoffeSiberian/truck-tools ***@***.***>
Cc : Angelius782 ***@***.***>; Author ***@***.***>
Objet : Re: [CoffeSiberian/truck-tools] French translation (Issue #10)


Hi there. I'm glad to hear that you like my utility and of course, all help is welcome for the app but at the moment I'm working on the templates for the translations. When these are available in the main branch of the project you are free to start translating the application using the templates

#9<https://github.com/CoffeSiberian/truck-tools/pull/9>

**Comment by CoffeSiberian** [comment]
As I told you. I am still working on this and you can check the progress in the development branch. Soon I will let you know exactly what will be the way for the translations and talking about the way the translations will be done I will try to see if I can use weblate but I am not sure about this service since it is paid but there is a version for open source projects that I have to look at

**Comment by Angelius782** [comment]
its ok ;)
